-- Adiciona campos de condições de pagamento em suppliers
ALTER TABLE public.suppliers
  ADD COLUMN IF NOT EXISTS has_credit boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_term_days integer,
  ADD COLUMN IF NOT EXISTS payment_notes text;

-- Tabela de Frete Mínimo ANTT
CREATE TABLE IF NOT EXISTS public.frete_minimo_antt (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cargo_type text,
  axis_count integer,
  table_kind text,
  distance_min_km integer,
  distance_max_km integer,
  ccd numeric,
  cc numeric,
  reference_month date,
  average_toll numeric,
  created_at timestamp with time zone DEFAULT now()
);

-- Índices auxiliares
CREATE INDEX IF NOT EXISTS idx_frete_minimo_antt_cargo_axis_kind
  ON public.frete_minimo_antt (cargo_type, axis_count, table_kind);

CREATE INDEX IF NOT EXISTS idx_frete_minimo_antt_distance_range
  ON public.frete_minimo_antt (distance_min_km, distance_max_km);

COMMENT ON TABLE public.frete_minimo_antt IS 'Tabela de frete mínimo ANTT por tipo de carga, eixos e faixa de distância.';
COMMENT ON COLUMN public.frete_minimo_antt.cargo_type IS 'Tipo de carga (ex: granel_liquido).';
COMMENT ON COLUMN public.frete_minimo_antt.axis_count IS 'Quantidade de eixos considerada na tabela.';
COMMENT ON COLUMN public.frete_minimo_antt.table_kind IS 'Tipo de tabela ANTT (ex: rodoviario).';
COMMENT ON COLUMN public.frete_minimo_antt.distance_min_km IS 'Início da faixa de distância em km.';
COMMENT ON COLUMN public.frete_minimo_antt.distance_max_km IS 'Fim da faixa de distância em km.';
COMMENT ON COLUMN public.frete_minimo_antt.ccd IS 'Custo de deslocamento (CCD) da tabela ANTT.';
COMMENT ON COLUMN public.frete_minimo_antt.cc IS 'Custo de carga (CC) da tabela ANTT.';
COMMENT ON COLUMN public.frete_minimo_antt.reference_month IS 'Mês/ano de referência da tabela ANTT.';
COMMENT ON COLUMN public.frete_minimo_antt.average_toll IS 'Valor médio de pedágio considerado na tabela.';
